print('Hello! My name is 口ひげを生やした帽子 .')
print('I was created in 2022')
print('Please, remind me your name.')
your_name = input("name:")
print('What a great name you have,' + your_name + '!')
print("Enter remainders of dividing your age by 3, 5 and 7.")
remainder3 = (float(input("на 3:")))
remainder5 = (float(input("на 5:")))
remainder7 = (float(input("на 7:")))
age = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15) % 105
print("Your age is " + str(age) + "; that's a good time to start programming!")
